### ISSUE TITLE
style2style fails to convert SLD to MapBox

### ISSUE THREAD

**Issue by Mhorttanainen** [GeoCat/bridge-style#61]
style2style command line tool requires 3 arguments, not 2 as stated in documentation and help

![style2style_arguments](https://user-images.githubusercontent.com/38314196/186128620-4173ee96-2cef-49f9-84b9-638bef540723.PNG)

**Comment by GeoSander** [comment]
Hi @Mhorttanainen,

Thanks for reporting.
This is indeed a bug. The arguments are not the problem though: it's the response from the `toGeostyler` function that does not return enough values. 

However, fixing this will not matter much, because what you should get instead is a `NotImplementedError`: you are trying to convert an SLD into MapBox GL JS. That conversion route has - in fact - not been implemented.

`bridgestyle` can only convert from **ArcGIS Pro** `.lyrx` or **QGIS** style (`qml`) input formats into **GeoStyler** (JSON). Using GeoStyler as an intermediate format, it can transform that into one of these output formats: 
- **SLD**
- **Mapfile**
- **MapBox/MapLibre GL JS**

So I'm sorry to inform you that any conversion from one of the output formats into _another_ output format (or any of the input formats for that matter) is not supported and likely never will be, unless someone wants to make a PR for it...

For now, the things I would like to improve here are:
- [ ] Raise `NotImplementedError` for all unsupported conversions
- [ ] Properly document what `style2style` supports

**Comment by Mhorttanainen** [comment]
I seem to be struggling also with gml - > json conversion..
![style2style_unsupported_format](https://user-images.githubusercontent.com/38314196/186142567-8edd64ea-d5f2-49f0-aa93-44a2850bf77e.PNG)
.

**Comment by GeoSander** [comment]
In my answer above I mentioned what is supported.
GML nor "pure" JSON are in this list. 

If you wish to convert to GeoStyler JSON, give the destination (dst) file a `.geostyler` extension.
However, GML is not even a style format, so that won't work.

**Comment by Mhorttanainen** [comment]
My bad, with small screen read .qml hopefully as .gml...
I am testing GeoCat Bridge and it works quite nicely with vector tile imports with Maptiler -plugin and Vector Tile Reader but only as single layers. Vectortile coloring in .gml format seems to be little different and harder to convert.
